### ISSUE TITLE
Installation fails on dunglas/frankenphp Docker image (based on php:8.4-zts)

### ISSUE THREAD

**Issue by riasvdv** [cachewerk/relay#155]
```
43.52 ### INSTALLING REMOTE MODULE relay ###
44.94 Downloading relay v0.9.0 (aarch64) from https://builds.r2.relay.so/v0.9.0/relay-v0.9.0-php8.4-debian-aarch64+libssl3.tar.gz... done.
46.05 Removing symbols from /usr/local/lib/php/extensions/no-debug-zts-20240924/relay.so... done (5676640 bytes saved).
46.06 Check if the relay module can be loaded... Error loading the "relay" extension:
46.08 
46.08 Warning: PHP Startup: Unable to load dynamic library 'relay.so' (tried: /usr/local/lib/php/extensions/no-debug-zts-20240924/relay.so (/usr/local/lib/php/extensions/no-debug-zts-20240924/relay.so: undefined symbol: core_globals), /usr/local/lib/php/extensions/no-debug-zts-20240924/relay.so.so (/usr/local/lib/php/extensions/no-debug-zts-20240924/relay.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

## Description

Happens with this Dockerfile (on a MacBook with an Apple chip):

```
FROM dunglas/frankenphp:1-php8.4 AS app

RUN install-php-extensions pcntl redis pdo_mysql opcache relay
```

**Comment by riasvdv** [comment]
Looks like the fact that it's a php-zts based image might be the issue

**Comment by tillkruss** [comment]
Yeah, we're having issues with our build pipeline. In the process of fixing it and will push new builds shortly.

**Comment by tillkruss** [comment]
We got this fixed in the nightly builds. Took forever to get CentOS7 and Ubuntu 16.04 to play along 🥲

Release coming shortly.

**Comment by riasvdv** [comment]
```
43.13 ### INSTALLING REMOTE MODULE relay ###
43.80 Downloading relay v0.9.1 (aarch64) from https://builds.r2.relay.so/v0.9.1/relay-v0.9.1-php8.4-debian-aarch64+libssl3.tar.gz... done.
45.05 Removing symbols from /usr/local/lib/php/extensions/no-debug-zts-20240924/relay.so... done (5688616 bytes saved).
45.06 Check if the relay module can be loaded... Error loading the "relay" extension:
45.07 
45.07 Warning: PHP Startup: Unable to load dynamic library 'relay.so' (tried: /usr/local/lib/php/extensions/no-debug-zts-20240924/relay.so (/usr/local/lib/php/extensions/no-debug-zts-20240924/relay.so: undefined symbol: core_globals), /usr/local/lib/php/extensions/no-debug-zts-20240924/relay.so.so (/usr/local/lib/php/extensions/no-debug-zts-20240924/relay.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

Still getting this with 0.9.1 looks like this is the actual error:

> undefined symbol: core_globals

Is Relay build for ZTS versions of PHP?

**Comment by szepeviktor** [comment]
It seems ZTS build are available only for x86_64.

**Comment by tillkruss** [comment]
@riasvdv We don't build ZTS builds anymore, unless a customer needs it.

**Comment by riasvdv** [comment]
That's a shame, FrankenPHP + Relay would make a great combo

**Comment by tillkruss** [comment]
> That's a shame, FrankenPHP + Relay would make a great combo

Which distros does it use?

**Comment by riasvdv** [comment]
https://github.com/dunglas/frankenphp/blob/main/docker-bake.hcl#L84

Looks like just the base zts images as base

**Comment by tillkruss** [comment]
@riasvdv We'll gladly add add the necessary builds if a customer needs it 👍

**Comment by fragkp** [comment]
@tillkruss No updates on this? I've tried to install the relay extension on our frankenphp 8.3 dockerfile, but ran into the following error:
```
145.8 ### INSTALLING REMOTE MODULE relay ###
146.7 Downloading relay v0.10.1 (aarch64) from https://builds.r2.relay.so/v0.10.1/relay-v0.10.1-php8.3-debian-aarch64.tar.gz... done.
147.9 Removing symbols from /usr/local/lib/php/extensions/no-debug-zts-20230831/relay.so... done (2249056 bytes saved).
147.9 Check if the relay module can be loaded... Error loading the "relay" extension:
147.9 
147.9 Warning: PHP Startup: Unable to load dynamic library 'relay.so' (tried: /usr/local/lib/php/extensions/no-debug-zts-20230831/relay.so (libssl.so.1.1: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-zts-20230831/relay.so.so (/usr/local/lib/php/extensions/no-debug-zts-20230831/relay.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

**Comment by tillkruss** [comment]
@fragkp: I don't recognize your username, if you're a customer, shoot me an email.
